In [88]:
import numpy as np

In [89]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [90]:
A

array([[10,  9, 10],
       [ 9,  5,  9],
       [10,  5,  8]], dtype=int32)

In [91]:
B

array([[-2,  3,  1],
       [ 3,  0, -1],
       [-2,  1,  0]], dtype=int32)

In [92]:
# Поэлементное умножение
A*B

array([[-20,  27,  10],
       [ 27,   0,  -9],
       [-20,   5,   0]], dtype=int32)

In [93]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[-13  40   1]
 [-21  36   4]
 [-21  38   5]]


In [94]:
# Матричное умножение
np.dot(A,B)

array([[-13,  40,   1],
       [-21,  36,   4],
       [-21,  38,   5]], dtype=int32)

In [95]:
# Матричное умножение
A@B

array([[-13,  40,   1],
       [-21,  36,   4],
       [-21,  38,   5]], dtype=int32)

In [96]:
# Порядок умножения AB != BA
B@A

array([[ 17,   2,  15],
       [ 20,  22,  22],
       [-11, -13, -11]], dtype=int32)

In [97]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[10  9  6  9  7]
 [ 7  9  5 10  6]
 [ 9  8  5  9  5]]
B:
 [[ 2  2]
 [ 3  0]
 [-2  0]
 [ 0 -2]
 [ 2  0]]


In [98]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[49,  2],
       [43, -6],
       [42,  0]], dtype=int32)

In [99]:
# Умножение прямоугольных матриц возможно не в любом порядке
# B@A

In [100]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [101]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 2  3 -2  0]
 [ 2 -1 -4  0]
 [ 3 -3  1  2]
 [ 1  2 -1  2]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 2  6  0  0]
 [ 2 -2  0  0]
 [ 3 -6  0 -2]
 [ 1  4  0 -2]]
DA:
 [[ 2  3 -2  0]
 [ 4 -2 -8  0]
 [ 0  0  0  0]
 [-1 -2  1 -2]]


In [102]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [103]:
# b@A

In [104]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [105]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [106]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [107]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [108]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [109]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
print(A@x)

[26 30]


In [110]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
C=B@A
print(C[0,3])

14


In [111]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([x, y, z])
print(A.T@A)

[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


In [112]:
import pandas as pd
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [113]:
P = Price_DF.values
C = Count_DF.values
salon_inc = (P*C)@(com)
print(salon_inc)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [114]:
P = Price_DF.values
C = Count_DF.values
styl_inc = (P*C)@(np.ones(5)-com)
print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


Обратная матрица в Python вычисляется с помощью функции numpy.linalg.inv():

In [115]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

В Python определитель считается с помощью функции np.linalg.det()

In [116]:
import numpy as np
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))
# -3.0000000000009

-2.9999999999999996


In [117]:
import numpy as np
A = np.matrix ("2, 0, 0; 0, 1, 0 ; 0, 0, 4")
print(np.linalg.det(A))

7.999999999999998


Давайте рассмотрим пример того, как вычислить ранг в Python. Для этого в библиотеке numpy существует специальная функция linalg.matrix_rank():

In [118]:
import numpy as np
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# 2

2


In [125]:
A = np.array([[1,0,3,5],
              [0,4,5,5],
              [0,0,0,0],
              [0,0,0,0]])
B = np.array([[0,0,0,0],
              [0,0,0,0],
              [0,1,1,4],
              [0,0,0,0]])
A
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

2
1
